# -*- coding: utf-8 -*-
"""CNN_V4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ya7XX-Vqviryz7ype_6XtN45pus48mVM
"""

from google.colab import drive
from keras.models import model_from_json
import numpy as np
import imageio
import cv2
drive.mount('/content/gdrive')

X = imageio.imread("/content/gdrive/MyDrive/Colab Notebooks/amostra1.png")
X = cv2.resize(X, (28, 28))
X = cv2.cvtColor(X, cv2.COLOR_BGR2GRAY)

import matplotlib.pyplot as plt
plt.imshow(X)
plt.show()

X = np.expand_dims(X, 2)
X = X.reshape(1, 28, 28, 1).astype('float32')  
X = X / 255

with open("/content/gdrive/MyDrive/Colab Notebooks/model.json" , "r") as json_file:
  load_model_json = json_file.read()
  model = model_from_json(load_model_json)
  model.load_weights("/content/gdrive/MyDrive/Colab Notebooks/model_w.h5")
  model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
  y = model.predict(X)
  
  print(np.argmax(y, axis=1))